spring.application.name=WsCancelations

spring.mail.host=smtp-mail.outlook.com
spring.mail.port=0000
spring.mail.username=quickorders@example.com
spring.mail.password=example
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Propiedad personalizada para usar como remitente
app.mail.from=quickorders@example.com
